---
title: "Lab_exer_1"
output:
  html_document:
    df_print: paged
date: "2024-02-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#install.packages(rvest") #install.packages("dplyr") #install.packages("polite") #install.packages("tidyverse") #install.packages("httr")

```{r}
library(rvest)
library(dplyr)
library(polite)
library(tidyverse)
library(httr)

amazonshoes <- data.frame()
scrapecat <-"shoes"

url1 <- "https://www.amazon.com.au/s?k=shoes&crid=3F8RISZ5QYEG7&sprefix=shoes%2Caps%2C265&ref=nb_sb_noss_1"

session1 <- bow(url1, user_agent = "For Educational Purposes")

Sys.sleep(10)

amazon <- read_html(url1)

shoes1 <- scrape(session1) %>%
  html_nodes("span.a-text-normal") %>%
  html_text

shoes1_100 <- shoes1[1:34]

pg_1name <- data.frame(Name = shoes1_100)
pg_1name

shoes1_price <- scrape(session1) %>%
  html_nodes("span.a-offscreen") %>%
  html_text

price1_100 <- shoes1_price[1:34]
price1_100

pg_1price <- data.frame(price = price1_100)
pg_1price

shoes1_ratings <- scrape(session1)%>%
  html_nodes ("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text

ratings1_100<- shoes1_ratings[1:34]
ratings1_100

pg_1ratings <- data.frame(ratings = ratings1_100)
pg_1ratings

shoes1_reviews <- scrape(session1)%>%
  html_nodes("span.a-size-base.s-underline-text")%>%
  html_text

reviews1_100 <- shoes1_reviews[1:34]
reviews1_100

pg_1reviews <- data.frame(num_of_ratings = reviews1_100)
pg_1reviews

amazonshoes <- rbind(amazonshoes, data.frame(category = scrapecat,
                                             Name = shoes1_100,
                                             Price = price1_100,
                                             Ratings = ratings1_100,
                                             Num_of_Reviews = reviews1_100))




#Page 2

url2 <- "https://www.amazon.com.au/s?k=shoes&page=2&crid=3F8RISZ5QYEG7&qid=1707956818&sprefix=shoes%2Caps%2C265&ref=sr_pg_2"

session2 <- bow(url2, user_agent = "For Educational Purposes")

Sys.sleep(10)

shoes2 <- scrape(session2) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
shoes2

shoes2_100 <- shoes2[1:34]
shoes2_100

pg_2name <- data.frame(name = shoes2_100)
pg_2name

shoes2_price <- scrape(session2) %>%
html_nodes("span.a-offscreen") %>%
html_text
shoes2_price

price2_100 <- shoes2_price[1:34]
price2_100

pg_2price <- data.frame(price = price2_100)
pg_2price

shoes2_ratings <- scrape(session2)%>%
html_nodes ("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
html_text
shoes2_ratings

ratings2_100<- shoes2_ratings[1:34]
ratings2_100

pg_2ratings <- data.frame(ratings = ratings2_100)
pg_2ratings

shoes2_reviews <- scrape(session2)%>%
html_nodes("span.a-size-base.s-underline-text")%>%
html_text
shoes2_reviews

reviews2_100 <- shoes2_reviews[1:34]
reviews2_100

pg_2reviews <- data.frame(num_of_ratings = reviews2_100)
pg_2reviews




amazonshoes <- rbind(amazonshoes, data.frame(category = scrapecat,
                                             Name = shoes2_100,
                                             Price = price2_100,
                                             Ratings = ratings2_100,
                                             Num_of_Reviews = reviews2_100))

#page 3


url3 <- "https://www.amazon.com.au/s?k=shoes&page=3&crid=3F8RISZ5QYEG7&qid=1707957555&sprefix=shoes%2Caps%2C265&ref=sr_pg_3"

session3 <- bow(url3, user_agent = "For Educational Purposes")

Sys.sleep(10)

shoes3 <- scrape(session3) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
shoes3

shoes3_100 <- shoes3[1:34]
shoes3_100

pg_3name <- data.frame(name = shoes3_100)
pg_3name

shoes3_price <- scrape(session3) %>%
html_nodes("span.a-offscreen") %>%
html_text
shoes3_price

price3_100 <- shoes3_price[1:34]
price3_100

pg_3price <- data.frame(price = price3_100)
pg_3price

shoes3_ratings <- scrape(session3)%>%
html_nodes ("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
html_text
shoes3_ratings

ratings3_100<- shoes3_ratings[1:34]
ratings3_100

pg_3ratings <- data.frame(ratings = ratings3_100)
pg_3ratings

shoes3_reviews <- scrape(session3)%>%
html_nodes("span.a-size-base.s-underline-text")%>%
html_text
shoes3_reviews

reviews3_100 <- shoes3_reviews[1:34]
reviews3_100

pg_3reviews <- data.frame(num_of_ratings = reviews3_100)
pg_3reviews




amazonshoes <- rbind(amazonshoes, data.frame(category = scrapecat,
                                             Name = shoes3_100,
                                             Price = price3_100,
                                             Ratings = ratings3_100,
                                             Num_of_Reviews = reviews3_100))


  
#View(amazonshoes)




```


#Toys 100 products


```{r}

amazontoys <- data.frame()
scrapecat <-"toys"

url2_1 <- "https://www.amazon.com.au/s?k=toys&crid=2M1Y2477F6BEZ&qid=1708159390&sprefix=toys%2Caps%2C335&ref=sr_pg_1"

session1 <- bow(url2_1, user_agent = "For Educational Purposes")

Sys.sleep(10)

amazon <- read_html(url2_1)

toys1 <- scrape(session1) %>%
  html_nodes("span.a-text-normal") %>%
  html_text

toys1_100 <- toys1[1:34]

pg_1name <- data.frame(Name = toys1_100)
pg_1name

toys1_price <- scrape(session1) %>%
  html_nodes("span.a-offscreen") %>%
  html_text

price1_100 <- toys1_price[1:34]
price1_100

pg_1price <- data.frame(price = price1_100)
pg_1price

toys1_ratings <- scrape(session1)%>%
  html_nodes ("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text

ratings1_100<- toys1_ratings[1:34]
ratings1_100

pg_1ratings <- data.frame(ratings = ratings1_100)
pg_1ratings

toys1_reviews <- scrape(session1)%>%
  html_nodes("span.a-size-base.s-underline-text")%>%
  html_text

reviews1_100 <- toys1_reviews[1:34]
reviews1_100

pg_1reviews <- data.frame(num_of_ratings = reviews1_100)
pg_1reviews

amazontoys <- rbind(amazontoys, data.frame(category = scrapecat,
                                             Name = toys1_100,
                                             Price = price1_100,
                                             Ratings = ratings1_100,
                                             Num_of_Reviews = reviews1_100))




#Page 2

url2_2 <- "https://www.amazon.com.au/s?k=toys&page=2&crid=2M1Y2477F6BEZ&qid=1708159908&sprefix=toys%2Caps%2C335&ref=sr_pg_2"

session2 <- bow(url2_2, user_agent = "For Educational Purposes")

Sys.sleep(10)

toys2 <- scrape(session2) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
toys2

toys2_100 <- toys2[1:34]
toys2_100

pg_2name <- data.frame(name = toys2_100)
pg_2name

toys2_price <- scrape(session2) %>%
html_nodes("span.a-offscreen") %>%
html_text
toys2_price

price2_100 <- toys2_price[1:34]
price2_100

pg_2price <- data.frame(price = price2_100)
pg_2price

toys2_ratings <- scrape(session2)%>%
html_nodes ("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
html_text
toys2_ratings

ratings2_100<- toys2_ratings[1:34]
ratings2_100

pg_2ratings <- data.frame(ratings = ratings2_100)
pg_2ratings

toys2_reviews <- scrape(session2)%>%
html_nodes("span.a-size-base.s-underline-text")%>%
html_text
toys2_reviews

reviews2_100 <- toys2_reviews[1:34]
reviews2_100

pg_2reviews <- data.frame(num_of_ratings = reviews2_100)
pg_2reviews




amazontoys <- rbind(amazontoys, data.frame(category = scrapecat,
                                             Name = toys2_100,
                                             Price = price2_100,
                                             Ratings = ratings2_100,
                                             Num_of_Reviews = reviews2_100))

#page 3


url2_3 <- "https://www.amazon.com.au/s?k=toys&page=3&crid=2M1Y2477F6BEZ&qid=1708159921&sprefix=toys%2Caps%2C335&ref=sr_pg_3"

session3 <- bow(url2_3, user_agent = "For Educational Purposes")

Sys.sleep(10)

toys3 <- scrape(session3) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
toys3

toys3_100 <- toys3[1:34]
toys3_100

pg_3name <- data.frame(name = toys3_100)
pg_3name

toys3_price <- scrape(session3) %>%
html_nodes("span.a-offscreen") %>%
html_text
toys3_price

price3_100 <- toys3_price[1:34]
price3_100

pg_3price <- data.frame(price = toys3_100)
pg_3price

toys3_ratings <- scrape(session3)%>%
html_nodes ("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
html_text
toys3_ratings

ratings3_100<- toys3_ratings[1:34]
ratings3_100

pg_3ratings <- data.frame(ratings = ratings3_100)
pg_3ratings

toys3_reviews <- scrape(session3)%>%
html_nodes("span.a-size-base.s-underline-text")%>%
html_text
toys3_reviews

reviews3_100 <- toys3_reviews[1:34]
reviews3_100

pg_3reviews <- data.frame(num_of_ratings = reviews3_100)
pg_3reviews




amazontoys <- rbind(amazontoys, data.frame(category = scrapecat,
                                             Name = toys3_100,
                                             Price = price3_100,
                                             Ratings = ratings3_100,
                                             Num_of_Reviews = reviews3_100))


  
#View(amazontoys)





```




#10 products yehaaaaaaaaaaaw


#1
```{r}

library(httr)
library(rvest)
library(selectr)

category <- "Shoes"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}

prodinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")

      Sys.sleep(5) 

            Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
            
            prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
            
            prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
            
            RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
            
            prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]

  amshoes <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  
  
  return(amshoes)
}


link1 <- "https://www.amazon.com.au/Crocs-Unisex-Adult-Classic-Cozzzy-Sandals/product-reviews/B0B63TTSTP/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- prodinfo(link1)


link2 <- "https://www.amazon.com.au/Crocs-Unisex-Adult-Classic-Cozzzy-Sandals/product-reviews/B0B63TTSTP/ref=cm_cr_getr_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- prodinfo(link2)


link3 <- "https://www.amazon.com.au/Crocs-Unisex-Adult-Classic-Cozzzy-Sandals/product-reviews/B0B63TTSTP/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- prodinfo(link3)


ProdRev1 <- rbind(pg1, pg2, pg3)

#view(ProdRev1)

```

#2
```{r}

library(httr)
library(rvest)
library(selectr)

category <- "Shoes"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}

prodinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")

  Sys.sleep(5) 

        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]

  amshoes <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amshoes)
}


link1 <- "https://www.amazon.com.au/Skechers-Womens-Uno-Lace-Up-Sneaker/product-reviews/B0CR97XY75/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- prodinfo(link1)


link2 <- "https://www.amazon.com.au/Skechers-Womens-Uno-Lace-Up-Sneaker/product-reviews/B0CR97XY75/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- prodinfo(link2)


link3 <- "https://www.amazon.com.au/Skechers-Womens-Uno-Lace-Up-Sneaker/product-reviews/B0CR97XY75/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- prodinfo(link3)


ProdRev2 <- rbind(pg1, pg2, pg3)

#view(ProdRev2)

```

#3
```{r}

library(httr)
library(rvest)
library(selectr)

category <- "Shoes"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}

prodinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")

  Sys.sleep(5) 

        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]

  amshoes <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amshoes)
}


link1 <- "https://www.amazon.com.au/Tommy-Hilfiger-Essential-Leather-Sneaker/product-reviews/B0CJ8CD94N/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- prodinfo(link1)


link2 <- "https://www.amazon.com.au/Tommy-Hilfiger-Essential-Leather-Sneaker/product-reviews/B0CJ8CD94N/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- prodinfo(link2)


link3 <- "https://www.amazon.com.au/Tommy-Hilfiger-Essential-Leather-Sneaker/product-reviews/B0CJ8CD94N/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg33 <- prodinfo(link3)


ProdRev3 <- rbind(pg1, pg2, pg3)

#view(ProdRev3)

```

#4
```{r}

category <- "Shoes"


library(httr)
library(rvest)
library(selectr)

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}

prodinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")

  Sys.sleep(5) 

        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]

        amshoes <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amshoes)
}


link1 <- "https://www.amazon.com.au/Salomon-Mens-Ultra-Pioneer-Hiking/product-reviews/B0CSKNJ82F/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page1 <- prodinfo(link1)


link2 <- "https://www.amazon.com.au/Salomon-Mens-Ultra-Pioneer-Hiking/product-reviews/B0CSKNJ82F/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
page2 <- prodinfo(link2)


link3 <- "https://www.amazon.com.au/Salomon-Mens-Ultra-Pioneer-Hiking/product-reviews/B0CSKNJ82F/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
page3 <- prodinfo(link3)


ProdRev4 <- rbind(page1, page2, page3)

#view(ProdRev4)

```

#5
```{r}


library(httr)
library(rvest)
library(selectr)

category <- "Shoes"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}

prodinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")

  Sys.sleep(5) 

        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]

  amshoes <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amshoes)
}


link1 <- "https://www.amazon.com.au/Crocs-Mens-LiteRide-Pacer-Shoe/product-reviews/B0B6BFZVM9/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- prodinfo(link1)


link2 <- "https://www.amazon.com.au/Crocs-Mens-LiteRide-Pacer-Shoe/product-reviews/B0B6BFZVM9/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- prodinfo(link2)


link3 <- "https://www.amazon.com.au/Crocs-Mens-LiteRide-Pacer-Shoe/product-reviews/B0B6BFZVM9/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- prodinfo(link3)


ProdRev5 <- rbind(pg1, pg2, pg3)

#view(ProdRev5)

```

#6
```{r}


library(httr)
library(rvest)
library(selectr)

category <- "Shoes"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}

prodinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")

  Sys.sleep(5) 

        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
  

  amshoes <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amshoes)
}


link1 <- "https://www.amazon.com.au/adidas-LYS50-Sportswear/product-reviews/B0CNPJQ75G/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- prodinfo(link1)


link2 <- "https://www.amazon.com.au/adidas-LYS50-Sportswear/product-reviews/B0CNPJQ75G/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- prodinfo(link2)


link3 <- "https://www.amazon.com.au/adidas-LYS50-Sportswear/product-reviews/B0CNPJQ75G/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- prodinfo(link3)


ProdRev6 <- rbind(pg1, pg2, pg3)

#view(ProdRev6)

```

#7
```{r}


library(httr)
library(rvest)
library(selectr)

category <- "Shoes"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}

prodinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")

  Sys.sleep(5) 

          Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
  
          prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
          prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
    
          RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
          prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]

  amshoes <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amshoes)
}


link1 <- "https://www.amazon.com.au/Skechers/product-reviews/B0CSF3CP3Z/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- prodinfo(link1)


link2 <- "https://www.amazon.com.au/Skechers/product-reviews/B0CSF3CP3Z/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- prodinfo(link2)


link3 <- "https://www.amazon.com.au/Skechers/product-reviews/B0CSF3CP3Z/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- prodinfo(link3)


ProdRev7 <- rbind(pg1, pg2, pg3)

#view(ProdRev7)

```

#8
```{r}


library(httr)
library(rvest)
library(selectr)

category <- "Shoes"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}

prodinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")

  Sys.sleep(5) 

          Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
          prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
          prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
          RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
          prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]

  amshoes <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amshoes)
}


link1 <- "https://www.amazon.com.au/ASICS-1011B492-002-Mens-Gel-Contend-8/product-reviews/B0BSN6H1MT/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- prodinfo(link1)


link2 <- "https://www.amazon.com.au/ASICS-1011B492-002-Mens-Gel-Contend-8/product-reviews/B0BSN6H1MT/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- prodinfo(link2)


link3 <- "https://www.amazon.com.au/ASICS-1011B492-002-Mens-Gel-Contend-8/product-reviews/B0BSN6H1MT/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- prodinfo(link3)


ProdRev8 <- rbind(pg1, pg2, pg3)

#view(ProdRev8)

```

#9
```{r}


library(httr)
library(rvest)
library(selectr)

category <- "Shoes"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}

prodinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")

  Sys.sleep(5) 

          Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
  
          prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
  
          prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
          RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
          prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]

  amshoes <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amshoes)
}


link1 <- "https://www.amazon.com.au/PUMA-Mens-Ignite-Fasten8-Disc/product-reviews/B09SBG442P/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- prodinfo(link1)


link2 <- "https://www.amazon.com.au/PUMA-Mens-Ignite-Fasten8-Disc/product-reviews/B09SBG442P/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- prodinfo(link2)


link3 <- "https://www.amazon.com.au/PUMA-Mens-Ignite-Fasten8-Disc/product-reviews/B09SBG442P/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- prodinfo(link3)


ProdRev9 <- rbind(pg1, pg2, pg3)

#view(ProdRev9)

```

#10
```{r}


library(httr)
library(rvest)
library(selectr)

category <- "Shoes"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}

prodinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")

  Sys.sleep(5) 

        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]

  amshoes <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amshoes)
}


link1 <- "https://www.amazon.com.au/Skechers/product-reviews/B0CVFYGDJ3/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- prodinfo(link1)


link2 <- "https://www.amazon.com.au/Skechers/product-reviews/B0CVFYGDJ3/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- prodinfo(link2)


link3 <- "https://www.amazon.com.au/Skechers/product-reviews/B0CVFYGDJ3/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- prodinfo(link3)


ProdRev10 <- rbind(pg1, pg2, pg3)

#view(ProdRev10)

```


```{r}

View_All_Products <- rbind(ProdRev1,
                           ProdRev2,
                           ProdRev3,
                           ProdRev4,
                           ProdRev5,
                           ProdRev6,
                           ProdRev7,
                           ProdRev8,
                           ProdRev9,
                           ProdRev10
                          )
View_All_Products

#view(View_All_Products)


```
